
theme="onedark"

[editor]
true-color=true
cursorline=true
mouse= true
bufferline="multiple"



[keys.insert]
C-c="normal_mode"
C-space=["normal_mode", "move_visual_line_down", "insert_mode"]
C-s=["normal_mode", ":write"]
C-a=["normal_mode", "goto_line_start", "insert_at_line_start"]
C-e=["normal_mode", "goto_line_end", "insert_at_line_end"]


[keys.normal]
# C-c="no_op"

#C-d=["move_prev_word_start", "move_next_word_start","search_selection", "select_mode"]

# Replace word under cursor 
"C-f" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]

# Duplicate line 
"C-d"= ["extend_to_line_bounds", "yank", "paste_after"]



S-tab=":buffer-next"
C-s=":write"

C-n=":new"
"ins"=":vnew"
C-q=":buffer-close"

C-up=[ "delete_selection", "move_visual_line_up", "paste_before"]
C-down=[ "delete_selection", "move_visual_line_down", "paste_before"]
C-space=["save_selection"]
C-b=":run-shell-command make"
C-c="collapse_selection"


"F2"=":config-open"
"F1"=":config-reload"
C-left="jump_backward"
C-right="jump_forward"

C-a=["goto_line_start"]
C-e=["goto_line_end"]



[keys.select]

"C-f" = ["search_selection", "extend_search_next"]




[keys.normal."m"]
m=["move_prev_word_start", "move_next_word_start"]
# c = ":config-reload" 

[keys.normal.space]
c="toggle_comments"
i=":format"
right="extend_to_line_end"
left="extend_to_line_start"


[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator"]
center=["file-name", "version-control" ]
right= ["position","position-percentage", "register", "spacer" ]
mode.normal="NORMAL"
mode.insert="INSERT"
mode.select="SELECT"

[editor.file-picker]
hidden = false


